import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List
import logging
from config import settings

logger = logging.getLogger(__name__)

class EmailService:
    def __init__(self, sender_email: str = None, sender_password: str = None):
        """
        Initialize email service with credentials from environment variables.
        Falls back to provided parameters or config defaults.
        """
        self.sender_email = sender_email or settings.EMAIL_SENDER
        self.sender_password = sender_password or settings.EMAIL_PASSWORD
        self.smtp_server = settings.EMAIL_SMTP_SERVER
        self.smtp_port = settings.EMAIL_SMTP_PORT

    def send_fraud_report(self, recipient_email: str, job_title: str, company: str, 
                         risk_score: float, red_flags: List[str]) -> dict:
        """
        Send a fraud report email to the specified recipient.
        """
        try:
            # Compose email
            subject = f"🚨 URGENT: Fake Job Posting Alert - {company} ({job_title})"
            
            # Create email body
            red_flags_text = "\n".join([f"  • {flag}" for flag in red_flags])
            
            body = f"""
URGENT FRAUD ALERT
==================

A job posting has been flagged as potentially fraudulent by our AI detection system.

POSTING DETAILS:
  Job Title: {job_title}
  Company (Claimed): {company}
  Risk Score: {risk_score}/100

DETECTED RED FLAGS:
{red_flags_text}

ACTION REQUIRED:
This posting has been automatically flagged for review. Please investigate and take appropriate action to protect job seekers from potential fraud.

Generated by: FraudLens - AI Job Fraud Detection System
"""
            
            # Create message
            message = MIMEMultipart("alternative")
            message["Subject"] = subject
            message["From"] = self.sender_email
            message["To"] = recipient_email
            
            # Attach plain text
            message.attach(MIMEText(body, "plain"))
            
            # Send email — automatically use SSL for port 465 (Gmail's SSL port)
            # or STARTTLS for port 587, since some networks block one but not
            # the other. This is driven entirely by EMAIL_SMTP_PORT in .env.
            if self.smtp_port == 465:
                with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port) as server:
                    server.login(self.sender_email, self.sender_password)
                    server.sendmail(self.sender_email, recipient_email, message.as_string())
            else:
                with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                    server.starttls()
                    server.login(self.sender_email, self.sender_password)
                    server.sendmail(self.sender_email, recipient_email, message.as_string())

            logger.info(f"Email sent successfully to {recipient_email}")
            
            return {
                "status": "success",
                "message": f"Fraud report sent to {recipient_email}",
                "recipient": recipient_email,
                "subject": subject
            }
            
        except smtplib.SMTPAuthenticationError:
            return {
                "status": "error",
                "message": "Email authentication failed. Please check your credentials and ensure you're using an App Password for Gmail.",
                "error_type": "auth_error"
            }
        except smtplib.SMTPException as e:
            return {
                "status": "error",
                "message": f"SMTP error occurred: {str(e)}",
                "error_type": "smtp_error"
            }
        except Exception as e:
            return {
                "status": "error",
                "message": f"Failed to send email: {str(e)}",
                "error_type": "general_error"
            }

# Create global instance
email_service = EmailService()
